import iphone from "../../images/product-image/iphone.webp";
import nokiaPhone from "../../images/product-image/nokiaPhone.webp";
import wirelessHeadphone from "../../images/product-image/wirelessHeadphone.webp";
import blackHeadphone from "../../images/product-image/blackHeadphone.webp";
import earbirdsHeadphone from "../../images/product-image/earbirdsHeadphone.webp";
import watch from "../../images/product-image/watch.webp";
import officialWatch from "../../images/product-image/officialWatch.webp";
import blackWatch from "../../images/product-image/blackWatch.webp";
import sunglass from "../../images/product-image/sunglass.webp";
import mattSunglass from "../../images/product-image/mattSunglass.webp";
import blackSunglass from "../../images/product-image/blackSunglass.webp";
import shoes from "../../images/product-image/shoes.webp";
import { Rating } from "@mui/material";

export const PRODUCTS = [
  {
    _id: 1,
    name: "Iphone 13 Pro Max",
    regularPrice: 2323,
    discountPrice: 1223,
    images: iphone,
    brand: "Apple",
    rating: 4.5,
    category: "Electronic",
  },
  {
    _id: 2,
    name: "Iphone 13 Pro Max",
    regularPrice: 2323,
    discountPrice: 1223,
    images: iphone,
    brand: "Apple",
    rating: 4.5,
    category: "Electronic",
  },
  {
    _id: 3,
    name: "Iphone 13 Pro Max",
    regularPrice: 2323,
    discountPrice: 1223,
    images: iphone,
    brand: "Apple",
    rating: 4.5,
    category: "Electronic",
  },
  {
    _id: 4,
    name: "Wireless Bluetooth Headphone",
    regularPrice: 2323,
    discountPrice: 1223,
    images: blackHeadphone,
    brand: "Xiaomi",
    rating: 4.5,
    category: "Electronic",
  },
  {
    _id: 5,
    name: "Earbirds Headphone",
    description: "string",
    regularPrice: 2323,
    discountPrice: 1223,
    images: earbirdsHeadphone,
    brand: "Xiaomi",
    rating: 4.5,
    category: "Electronic",
  },
  {
    _id: 6,
    name: "Wireless Headphone",
    regularPrice: 2323,
    discountPrice: 1223,
    images: wirelessHeadphone,
    brand: "Xiaomi",
    rating: 4.5,
    category: "Electronic",
  },
  {
    _id: 7,
    name: "Nokia Andriod",
    regularPrice: 2323,
    discountPrice: 1223,
    images: nokiaPhone,
    brand: "Nokia",
    rating: 4.5,
    category: "Electronic",
  },
  {
    _id: 8,
    name: "Nokia Andriod",
    regularPrice: 2323,
    discountPrice: 1223,
    images: nokiaPhone,
    brand: "Nokia",
    rating: 4.5,
    category: "Electronic",
  },
  {
    _id: 9,
    name: "Nokia Andriod",
    regularPrice: 2323,
    discountPrice: 1223,
    images: nokiaPhone,
    brand: "Nokia",
    rating: 4.5,
    category: "Electronic",
  },
  {
    _id: 10,
    name: "Classic Rolex Watch",
    regularPrice: 2323,
    discountPrice: 1223,
    images: watch,
    brand: "Rolex",
    rating: 4.5,
    category: "Fashion",
  },
  {
    _id: 11,
    name: "Classic Rolex Watch",
    regularPrice: 2323,
    discountPrice: 1223,
    images: officialWatch,
    brand: "Rolex",
    rating: 4.5,
    category: "Fashion",
  },
  {
    _id: 12,
    name: "Classic Rolex Watch",
    regularPrice: 2323,
    discountPrice: 1223,
    images: blackWatch,
    brand: "Rolex",
    rating: 4.5,
    category: "Fashion",
  },
  {
    _id: 13,
    name: "Black Sunglass",
    regularPrice: 2323,
    discountPrice: 1223,
    images: sunglass,
    brand: "",
    rating: 4.5,
    category: "Fashion",
  },
  {
    _id: 14,
    name: "Matt Sunglass",
    regularPrice: 2323,
    discountPrice: 1223,
    images: mattSunglass,
    brand: "",
    rating: 4.5,
    category: "Fashion",
  },
  {
    _id: 15,
    name: "Black Sunglass",
    regularPrice: 2323,
    discountPrice: 1223,
    images: blackSunglass,
    brand: "",
    rating: 4.5,
    category: "Fashion",
  },
  {
    _id: 16,
    name: "Sport Shoes",
    regularPrice: 2323,
    discountPrice: 1223,
    images: shoes,
    brand: "Xiaomi",
    rating: 4.5,
    category: "Fashion",
  },
];
